Repository selsa-inube/inubekit-tabs, pull requests merged in 2024-04, with the labels that each got.

#5 Adjust and export interfaces
  package-lock.json
  package.json
  src/Tabs/Tab/props.ts
  src/Tabs/props.ts
  src/index.ts
Labels: minor

#6 Publish new version 2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#7 Add auto publish
  .autorc.json
  .github/workflows/auto-release.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement

#8 Update workflow in order to avoid merges with failed builds
  .github/workflows/auto-release.yml
Labels: minor
